In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9574074074074074

In [6]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [7]:
sv=SVC()
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.9925925925925926

In [12]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_i,test_i in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_i,test_i)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [15]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [16]:
score_l=[]
score_s=[]
score_r=[]

for train_index,test_index in folds.split(digits.data,digits.target):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  score_l.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
  score_s.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  score_r.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

Stratified K fold

In [17]:
score_l

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [18]:
score_s

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [19]:
score_r

[0.9432387312186978, 0.9565943238731218, 0.9165275459098498]

In [22]:
score_l.clear()
score_r.clear()
score_s.clear()
for train_index,test_index in kf.split(digits.data,digits.target):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  score_l.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
  score_s.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  score_r.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

Kfold

In [23]:
score_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [24]:
score_s

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [25]:
score_r

[0.9332220367278798, 0.9565943238731218, 0.9248747913188647]

In [27]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [28]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [29]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93888889, 0.90277778, 0.9637883 , 0.9637883 , 0.93036212])